.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. mindblockchain_qt test_mindblockchain_qt
clean: FORCE
	$(MAKE) -C .. mindblockchain_qt_clean test_mindblockchain_qt_clean
check: FORCE
	$(MAKE) -C .. test_mindblockchain_qt_check
mindblockchain-qt mindblockchain-qt.exe: FORCE
	 $(MAKE) -C .. mindblockchain_qt
